# Foursquare
CLIENT_ID = "YOUR_KEY_HERE"
CLIENT_SECRET = "YOUR_KEY_HERE"
CATEGORY_ID = "4d4b7105d754a06376d81259" # Nightlife

# Yelp
CONSUMER_KEY = "YOUR_KEY_HERE"
CONSUMER_SECRET = "YOUR_KEY_HERE"
TOKEN = "YOUR_KEY_HERE"
TOKEN_SECRET = "YOUR_KEY_HERE"

# Google Places
GOOGLE_API_KEY = "YOUR_KEY_HERE"